version: '3.9'
services:
  g2sg-app:
    build: .
    container_name: g2sg-app
    platform: linux/amd64
    x-kubernetes:
      imagePullPolicy: IfNotPresent
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@g2sg-postgres:5432/${POSTGRES_DB}?schema=public
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}

  g2sg-postgres:
    image: postgres:16
    x-kubernetes:
      imagePullPolicy: IfNotPresent
    container_name: g2sg-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - g2sg-data:/var/lib/postgresql/data

volumes:
  g2sg-data: