version: '3.9'
x-kubernetes:
  name: g2sg
  namespace: g2sg
services:
  g2sg-app:
    build: .
    image: maayanlab/g2sg-app:0.7.0
    platform: linux/amd64
    x-kubernetes:
      imagePullPolicy: IfNotPresent
      annotations:
        maayanlab.cloud/ingress: https://genesetcart.cfde.cloud
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@g2sg-postgres:5432/${POSTGRES_DB}?schema=public
      - NEXTAUTH_URL=https://genesetcart.cfde.cloud
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHON_API_BASE=http://g2sg-flask:8000
      - PUBLIC_USER_ID=${PUBLIC_USER_ID}
      - PUBLIC_URL=https://genesetcart.cfde.cloud
      - NEXTAUTH_KEYCLOAK=${NEXTAUTH_KEYCLOAK}
      - NEXT_PUBLIC_GA_MEASUREMENT_ID=${NEXT_PUBLIC_GA_MEASUREMENT_ID}

  g2sg-postgres:
    image: postgres:16
    x-kubernetes:
      imagePullPolicy: IfNotPresent
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - g2sg-data:/var/lib/postgresql/data

  g2sg-flask:
    build: ../python-backend
    image: maayanlab/g2sg-flask:0.7.0
    platform: linux/amd64
    x-kubernetes:
      imagePullPolicy: IfNotPresent
    ports: 
    - 8000
    environment:
      PORT: 8000

  g2sg-legacy-redirect:
    image: maayanlab/proxy:1.2.9
    x-kubernetes:
      imagePullPolicy: IfNotPresent
      annotations:
        maayanlab.cloud/ingress: https://g2sg.cfde.cloud
    ports:
      - 80
    environment:
      nginx_server_name: https://g2sg.cfde.cloud
      nginx_redirect_00: /(.*) https://genesetcart.cfde.cloud/$$1

volumes:
  g2sg-data:
    x-kubernetes:
      size: 8Gi
      class: gp2
